### ISSUE TITLE
Fix change password issue

### ISSUE THREAD

**Issue by adevadeh** [kudelabs/hackpad#1]
Many users report that they are unable to change their password. This needs to be fixed.

**Comment by ahonn** [comment]
I found commented [`_sendPasswordChangeConfirmation ()`](https://github.com/kudelabs/collabpad/blob/master/etherpad/src/etherpad/control/pro/account_settings_control.js#L230) can solve this problem, but it will not send reminder email.

**Comment by adevadeh** [comment]
another report:

> Using Chrome.
> Fails to recognize my password every time.
> Select Forgot password.
> 

"Oops! A server error occured. It's been logged.
Please email <devops@kudelabs.com> if this persist"

**Comment by adevadeh** [comment]
because email is not configured or because the code doesn't send email?
